import type { ClueDef, FactDef } from '@meridien/engine';

/**
 * I trentaquattro indizi del caso.
 * La definizione è statica: ogni variante decide soltanto dove si trovano,
 * in quale atto compaiono e quanto contano. I fatti che gli indizi rivelano
 * sono osservazioni, non interpretazioni: la lettura cambia con la variante,
 * il rilievo no.
 */

export const clues: ClueDef[] = [
  // ── la vasca e la terrazza ────────────────────────────────────────────────
  {
    id: 'clue.orologio-fondo',
    title: 'L’orologio sul fondo',
    text: 'Sul fondo della vasca svuotata, contro la griglia di scarico, un orologio subacqueo con il cinturino slacciato. Le lancette sono ferme sulle 23:47. Il vetro è intatto.',
    kind: 'fisico',
    icon: 'orologio',
    reveals: ['fact.orologio-fermo-2347'],
    requires: [],
    objectId: 'obj.orologio',
  },
  {
    id: 'clue.ghiera-orologio',
    title: 'La ghiera girata',
    text: 'La ghiera graduata è ferma su quaranta minuti e la corona è estratta di uno scatto. Un orologio con la corona fuori non cammina: qualcuno lo ha fermato con le dita, non l’acqua.',
    kind: 'fisico',
    icon: 'lente',
    reveals: ['fact.orologio-manomesso'],
    requires: [],
    objectId: 'obj.orologio',
  },
  {
    id: 'clue.ringhiera-terrazza',
    title: 'La vernice del parapetto',
    text: 'Sul parapetto di ponente la vernice d’aprile è grattata per una spanna, all’altezza del corrimano. Sotto, il ferro è lucido. Il resto della ringhiera è coperto di salino.',
    kind: 'osservazione',
    icon: 'ringhiera',
    reveals: ['fact.segno-ringhiera'],
    requires: [],
  },
  {
    id: 'clue.porta-vetri',
    title: 'La porta a vetri',
    text: 'La porta a vetri della terrazza è chiusa a chiave dall’interno della hall. Il registro della direzione segna la chiusura alle 23:20, come ogni sera di temporale.',
    kind: 'documento',
    icon: 'porta',
    reveals: ['fact.terrazza-chiusa-2320'],
    requires: [],
  },
  {
    id: 'clue.impronte-bagnate',
    title: 'Le impronte sulla soglia',
    text: 'Sulla soglia della porta a vetri due impronte bagnate, suola liscia, punte rivolte verso l’interno. Chi le ha lasciate stava rientrando, non uscendo.',
    kind: 'osservazione',
    icon: 'impronta',
    reveals: ['fact.impronte-verso-interno'],
    requires: [],
  },
  {
    id: 'clue.telo-piscina',
    title: 'Il telo di copertura',
    text: 'Il telo della vasca è arrotolato sul bordo di levante, ma gli occhielli del lato corto sono liberi e le cime pendono. Bacigalupo lo aveva fissato e firmato la scheda alle 21:40.',
    kind: 'fisico',
    icon: 'telo',
    reveals: ['fact.telo-spostato'],
    requires: [],
  },
  {
    id: 'clue.scala-vasca',
    title: 'La scaletta della vasca',
    text: 'La scaletta di ferro della vasca è stata riverniciata a settembre. Sui due montanti, all’altezza delle mani, la vernice è segnata da quattro strisce fresche.',
    kind: 'fisico',
    icon: 'scaletta',
    reveals: ['fact.scaletta-usata'],
    requires: [],
  },
  {
    id: 'clue.giaccavento',
    title: 'La cerata appesa',
    text: 'La cerata gialla di Vanzetti è appesa al gancio del passaggio di servizio. Fuori è bagnata, dentro è perfettamente asciutta: l’ha portata qualcuno che non la indossava.',
    kind: 'fisico',
    icon: 'cerata',
    reveals: ['fact.cerata-asciutta'],
    requires: [],
  },

  // ── l’orologio, i nomi, l’identità ────────────────────────────────────────
  {
    id: 'clue.incisione-orologio',
    title: 'L’incisione sul fondello',
    text: 'Sul fondello dell’orologio, in caratteri di punteruolo: «A I. B. — 1962». Nessuno degli ospiti registrati come Vanzetti ha quelle iniziali.',
    kind: 'fisico',
    icon: 'incisione',
    reveals: ['fact.orologio-inciso-ib'],
    requires: [],
    objectId: 'obj.orologio',
  },
  {
    id: 'clue.certificato-immersione',
    title: 'Il brevetto del 1962',
    text: 'Copia del brevetto rilasciato dopo il recupero dell’Aurelia. In alto due nominativi, in calce una sola firma, ripassata due volte sopra un tratto più chiaro.',
    kind: 'documento',
    icon: 'brevetto',
    reveals: ['fact.impresa-1962-due-uomini'],
    requires: [],
  },
  {
    id: 'clue.registro-arrivi',
    title: 'Il registro degli arrivi',
    text: 'Alla data del 2 ottobre il registro porta due righe consecutive con lo stesso indirizzo di Chioggia: una intestata a Vanzetti E., l’altra a Barigazzi I. Camera assegnata: la 214, una sola.',
    kind: 'documento',
    icon: 'registro',
    reveals: ['fact.due-vanzetti-registro'],
    requires: [],
    objectId: 'obj.registro',
  },
  {
    id: 'clue.tessera-marina',
    title: 'La tessera ministeriale',
    text: 'Tessera di abilitazione al lavoro subacqueo. La fotografia è stata scollata e riapplicata: il timbro a secco continua sul cartoncino ma si interrompe sull’immagine.',
    kind: 'documento',
    icon: 'tessera',
    reveals: ['fact.tessera-alterata'],
    requires: [],
  },

  // ── i debiti ──────────────────────────────────────────────────────────────
  {
    id: 'clue.cambiale',
    title: 'Il pagherò da quattro milioni',
    text: 'Modulo bollato, firma di Vanzetti in turchino, scadenza 5 ottobre 1967. Il nome del beneficiario è stato scritto in un secondo momento, con inchiostro nero.',
    kind: 'documento',
    icon: 'cambiale',
    reveals: ['fact.debito-scadenza-5'],
    requires: [],
    objectId: 'obj.cambiale',
  },
  {
    id: 'clue.libretto-casino',
    title: 'Il libretto del casinò',
    text: 'Tre serate di seguito, dal primo ottobre. Le colonne di destra scendono e non risalgono. All’ultima riga, a matita, una sigla che non è del contabile.',
    kind: 'documento',
    icon: 'libretto',
    reveals: ['fact.perdite-casino'],
    requires: [],
  },
  {
    id: 'clue.lettera-banca',
    title: 'La lettera della banca',
    text: 'Raccomandata di una filiale di Genova, aperta con il dito: conto scoperto, fido revocato, invito a presentarsi entro il 10. La busta era in fondo alla valigia.',
    kind: 'documento',
    icon: 'lettera',
    reveals: ['fact.conto-scoperto'],
    requires: [],
  },
  {
    id: 'clue.polizza-vita',
    title: 'La polizza della squadra',
    text: 'Polizza infortuni sulla squadra di immersione, beneficiaria la società armatrice. La decorrenza è stata anticipata a penna dal 1° novembre al 1° ottobre, con sigla di conferma.',
    kind: 'documento',
    icon: 'polizza',
    reveals: ['fact.polizza-beneficiaria'],
    requires: [],
  },
  {
    id: 'clue.ricevuta-saldata',
    title: 'La ricevuta di saldo',
    text: 'Ricevuta liberatoria per quattro milioni, datata 4 ottobre. Il timbro tondo è stato battuto a mano e il numero progressivo viene dopo quello di una ricevuta del giorno 6.',
    kind: 'documento',
    icon: 'ricevuta',
    reveals: ['fact.debito-saldato-quel-giorno'],
    requires: [],
  },
  {
    id: 'clue.assegno-strappato',
    title: 'L’assegno nel cestino',
    text: 'Nel cestino di ottone della hall, un assegno strappato in quattro e ricomposto sul bancone: importo quattro milioni, firma di Vanzetti, sopra il tratto la parola «no».',
    kind: 'fisico',
    icon: 'assegno',
    reveals: ['fact.assegno-rifiutato'],
    requires: [],
  },

  // ── le fotografie ─────────────────────────────────────────────────────────
  {
    id: 'clue.provino-contatto',
    title: 'Il foglio di provini',
    text: 'Dodici riquadri numerati, undici stampati. Al posto del nono c’è un rettangolo bianco: il negativo non è passato sotto l’ingranditore insieme agli altri.',
    kind: 'documento',
    icon: 'provini',
    reveals: ['fact.posa-nove-mancante'],
    requires: [],
    objectId: 'obj.provini',
  },
  {
    id: 'clue.negativo-graffiato',
    title: 'Il negativo numero nove',
    text: 'Nella striscia, il fotogramma nove è rigato in diagonale da un graffio profondo, fatto a pellicola già asciutta. Gli altri undici sono intatti.',
    kind: 'fisico',
    icon: 'negativo',
    reveals: ['fact.negativo-danneggiato'],
    requires: [],
  },
  {
    id: 'clue.fotografia-terrazza',
    title: 'La stampa della terrazza',
    text: 'Una stampa 13×18 appesa al filo, ancora umida: la pensilina di ponente, la pioggia in controluce e due figure sotto la pensilina, non una.',
    kind: 'fisico',
    icon: 'fotografia',
    reveals: ['fact.due-figure-terrazza'],
    requires: [],
    objectId: 'obj.macchina-foto',
  },
  {
    id: 'clue.orario-flash',
    title: 'Il taccuino di posa',
    text: 'Il taccuino della fotografa segna per ogni scatto ora e diaframma. Riga nove: «23:12 — f/2 — pensilina». È l’unica riga scritta a matita invece che a penna.',
    kind: 'documento',
    icon: 'taccuino',
    reveals: ['fact.posa-nove-alle-2312'],
    requires: [],
  },
  {
    id: 'clue.bacinella-fissaggio',
    title: 'La bacinella tiepida',
    text: 'Alle 00:30 la bacinella del fissaggio è ancora tiepida e il termometro a immersione segna diciannove gradi. Le pinze sono appoggiate bagnate sul bordo.',
    kind: 'osservazione',
    icon: 'bacinella',
    reveals: ['fact.camera-oscura-usata-tardi'],
    requires: [],
  },
  {
    id: 'clue.foto-vecchia',
    title: 'La fotografia del 1962',
    text: 'Sul tavolo di montaggio una stampa del 1962, tagliata a metà con la taglierina. Resta la parte con il volto; manca quella con le mani e con il numero cucito sulla muta.',
    kind: 'fisico',
    icon: 'fotografia-vecchia',
    reveals: ['fact.foto-1962-ritagliata'],
    requires: [],
  },

  // ── i segnali e la costa ──────────────────────────────────────────────────
  {
    id: 'clue.lampada-segnali',
    title: 'La lampada a otturatore',
    text: 'Nel ripostiglio del passaggio, la lampada da segnalazione è fuori posto e la batteria è scarica. Bacigalupo l’aveva provata mercoledì e l’aveva trovata carica.',
    kind: 'fisico',
    icon: 'lampada',
    reveals: ['fact.lampada-usata'],
    requires: [],
    objectId: 'obj.lampada',
  },
  {
    id: 'clue.quaderno-faro',
    title: 'Il quaderno del faro',
    text: 'Il guardiano di Capo Mele annota ogni sera le luci anomale. Alla riga del 4 ottobre: «23:05 — tre lampi corti da terra, direzione punta, non regolamentari».',
    kind: 'documento',
    icon: 'quaderno',
    reveals: ['fact.segnali-2305'],
    requires: [],
  },
  {
    id: 'clue.testimonianza-pescatore',
    title: 'Il verbale del pescatore',
    text: 'Verbale raccolto a Laigueglia: il pescatore Sciaccaluga, al riparo sotto la punta, dichiara di aver visto una luce bassa spegnersi verso il largo alle 23:10 circa.',
    kind: 'testimonianza',
    icon: 'verbale',
    reveals: ['fact.luce-in-mare-2310'],
    requires: [],
  },
  {
    id: 'clue.barca-molo',
    title: 'La cima del gozzo',
    text: 'Il gozzo di servizio è al suo gancio, ma la cima è riannodata con un nodo doppio che al Méridien non usa nessuno. Sul paiolo c’è acqua di mare, non di pioggia.',
    kind: 'fisico',
    icon: 'cima',
    reveals: ['fact.gozzo-mosso'],
    requires: [],
  },
  {
    id: 'clue.carta-nautica',
    title: 'La carta nautica segnata',
    text: 'Foglio 921, piegato in otto. Sulla secca del Grillo, a matita copiativa, una croce e accanto due cifre: «11». Il resto della carta non ha annotazioni.',
    kind: 'documento',
    icon: 'carta',
    reveals: ['fact.punto-segnato-secca'],
    requires: [],
    objectId: 'obj.carta-nautica',
  },

  // ── l’albergo ─────────────────────────────────────────────────────────────
  {
    id: 'clue.registro-chiavi',
    title: 'Il registro delle chiavi',
    text: 'La chiave della terrazza risulta riconsegnata alle 23:20 e ritirata di nuovo alle 23:40. Accanto alla seconda riga la casella della firma è vuota.',
    kind: 'documento',
    icon: 'chiavi',
    reveals: ['fact.chiave-terrazza-ritirata-2340'],
    requires: [],
  },
  {
    id: 'clue.centralino-chiamata',
    title: 'Il foglio del centralino',
    text: 'Foglio delle interurbane: 22:35, Sanremo 21-4-40, due minuti, addebito camera 214. È l’ultima chiamata prima che la linea cada.',
    kind: 'documento',
    icon: 'centralino',
    reveals: ['fact.telefonata-sanremo-2235'],
    requires: [],
  },
  {
    id: 'clue.scarpe-asciutte',
    title: 'Le scarpe da sera',
    text: 'Davanti alla 209, un paio di scarpe da sera messe fuori per la lucidatura. Le suole sono asciutte e il tacco è pulito: chi le portava non è uscito con la pioggia.',
    kind: 'osservazione',
    icon: 'scarpe',
    reveals: ['fact.scarpe-asciutte'],
    requires: [],
  },
  {
    id: 'clue.ombrello-corridoio',
    title: 'L’ombrello del corridoio',
    text: 'La Coldani segna sul quaderno delle camere: «23:50, ombrello gocciolante appoggiato alla porta della 214, moquette da asciugare». L’ombrello alle 00:20 non c’era più.',
    kind: 'testimonianza',
    icon: 'ombrello',
    reveals: ['fact.qualcuno-rientrato-2350'],
    requires: [],
  },
  {
    id: 'clue.quadro-elettrico',
    title: 'Il quadro della piscina',
    text: 'Nel quadro del passaggio la linea dei fari della vasca è aperta a mano, non per intervento del salvavita. La levetta è stata alzata alle 22:10, prima del temporale forte.',
    kind: 'fisico',
    icon: 'quadro',
    reveals: ['fact.luci-piscina-spente-2210'],
    requires: [],
  },
];

/**
 * I fatti che gli indizi mettono a disposizione, più i quattro fatti comuni
 * noti a tutti dalla prima scena. Ogni variante li riprende e vi aggiunge le
 * proprie affermazioni non provate.
 */
const BASE_FACTS: FactDef[] = [
  { id: 'fact.orologio-fermo-2347', text: 'L’orologio trovato nella vasca è fermo sulle 23:47.', kind: 'oggetto', common: false },
  { id: 'fact.orologio-manomesso', text: 'L’orologio è stato fermato a mano, con la corona estratta, non dall’acqua né dall’urto.', kind: 'oggetto', common: false },
  { id: 'fact.segno-ringhiera', text: 'Sul parapetto di ponente la vernice è grattata di fresco per una spanna.', kind: 'luogo', common: false },
  { id: 'fact.terrazza-chiusa-2320', text: 'La porta a vetri della terrazza è stata chiusa a chiave alle 23:20.', kind: 'tempo', common: false },
  { id: 'fact.impronte-verso-interno', text: 'Le impronte bagnate sulla soglia sono rivolte verso l’interno: qualcuno è rientrato.', kind: 'luogo', common: false },
  { id: 'fact.telo-spostato', text: 'Il telo della vasca, fissato alle 21:40, è stato liberato su un lato dopo.', kind: 'oggetto', common: false },
  { id: 'fact.scaletta-usata', text: 'La scaletta della vasca vuota è stata usata dopo la riverniciatura di settembre.', kind: 'oggetto', common: false },
  { id: 'fact.cerata-asciutta', text: 'La cerata di Vanzetti è appesa nel passaggio, bagnata fuori e asciutta dentro.', kind: 'oggetto', common: false },
  { id: 'fact.orologio-inciso-ib', text: 'L’orologio porta inciso «A I. B. — 1962»: non è intestato a Elio Vanzetti.', kind: 'oggetto', common: false },
  { id: 'fact.impresa-1962-due-uomini', text: 'Il brevetto del 1962 nomina due uomini e porta una firma sola, ripassata.', kind: 'relazione', common: false },
  { id: 'fact.due-vanzetti-registro', text: 'Il registro segna due arrivi dallo stesso indirizzo di Chioggia e una sola camera.', kind: 'relazione', common: false },
  { id: 'fact.tessera-alterata', text: 'La fotografia della tessera ministeriale è stata scollata e riapplicata.', kind: 'oggetto', common: false },
  { id: 'fact.debito-scadenza-5', text: 'Vanzetti doveva quattro milioni con scadenza 5 ottobre 1967.', kind: 'relazione', common: false },
  { id: 'fact.perdite-casino', text: 'Vanzetti ha perso al casinò per tre serate consecutive dal primo ottobre.', kind: 'relazione', common: false },
  { id: 'fact.conto-scoperto', text: 'Il conto di Vanzetti era scoperto e il fido revocato.', kind: 'relazione', common: false },
  { id: 'fact.polizza-beneficiaria', text: 'La polizza sulla squadra ha per beneficiaria la società armatrice, con decorrenza anticipata al 1° ottobre.', kind: 'relazione', common: false },
  { id: 'fact.debito-saldato-quel-giorno', text: 'Esiste una ricevuta di saldo datata 4 ottobre, con numero progressivo fuori ordine.', kind: 'oggetto', common: false },
  { id: 'fact.assegno-rifiutato', text: 'Un assegno di quattro milioni firmato Vanzetti è stato strappato e gettato nella hall.', kind: 'oggetto', common: false },
  { id: 'fact.posa-nove-mancante', text: 'Sul foglio di provini manca la nona posa.', kind: 'oggetto', common: false },
  { id: 'fact.negativo-danneggiato', text: 'Il negativo numero nove è stato graffiato a pellicola asciutta.', kind: 'oggetto', common: false },
  { id: 'fact.due-figure-terrazza', text: 'Una stampa della terrazza mostra due figure sotto la pensilina di ponente.', kind: 'luogo', common: false },
  { id: 'fact.posa-nove-alle-2312', text: 'Il taccuino di posa data la nona fotografia alle 23:12.', kind: 'tempo', common: false },
  { id: 'fact.camera-oscura-usata-tardi', text: 'La camera oscura è stata usata fino a poco prima delle 00:30.', kind: 'tempo', common: false },
  { id: 'fact.foto-1962-ritagliata', text: 'Una stampa del 1962 è stata tagliata togliendo mani e numero della muta.', kind: 'oggetto', common: false },
  { id: 'fact.lampada-usata', text: 'La lampada da segnalazione del passaggio è stata usata quella sera fino a scaricare la batteria.', kind: 'oggetto', common: false },
  { id: 'fact.segnali-2305', text: 'Alle 23:05 dal promontorio partono tre lampi corti verso il largo.', kind: 'tempo', common: false },
  { id: 'fact.luce-in-mare-2310', text: 'Alle 23:10 una luce bassa si spegne al largo della punta.', kind: 'tempo', common: false },
  { id: 'fact.gozzo-mosso', text: 'Il gozzo di servizio è stato usato e riormeggiato con un nodo estraneo all’albergo.', kind: 'oggetto', common: false },
  { id: 'fact.punto-segnato-secca', text: 'Sulla carta nautica la secca del Grillo è segnata a matita con una croce e il numero 11.', kind: 'oggetto', common: false },
  { id: 'fact.chiave-terrazza-ritirata-2340', text: 'La chiave della terrazza è stata ritirata di nuovo alle 23:40 senza firma.', kind: 'tempo', common: false },
  { id: 'fact.telefonata-sanremo-2235', text: 'Alle 22:35 parte dalla hall una interurbana per Sanremo addebitata alla 214.', kind: 'tempo', common: false },
  { id: 'fact.scarpe-asciutte', text: 'Davanti alla 209 le scarpe da sera messe fuori hanno suole asciutte.', kind: 'oggetto', common: false },
  { id: 'fact.qualcuno-rientrato-2350', text: 'Alle 23:50 un ombrello gocciolante compare alla porta della 214.', kind: 'tempo', common: false },
  { id: 'fact.luci-piscina-spente-2210', text: 'I fari della vasca sono stati spenti a mano alle 22:10.', kind: 'tempo', common: false },
  // fatti comuni, noti a tutti dalla prima scena
  { id: 'fact.temporale', text: 'Un temporale investe la punta dalle 21:20 all’una, con vento di libeccio.', kind: 'tempo', common: true },
  { id: 'fact.piscina-svuotata', text: 'La piscina è stata svuotata nel pomeriggio del 4 ottobre per la chiusura di stagione.', kind: 'luogo', common: true },
  { id: 'fact.corpo-non-trovato', text: 'Di Elio Vanzetti non è stato ritrovato nulla: né in mare, né a riva, né nella vasca.', kind: 'persona', common: true },
  { id: 'fact.uscita-2250', text: 'Elio Vanzetti è stato visto uscire sulla terrazza alle 22:50 e non è rientrato dalla porta a vetri.', kind: 'tempo', common: true },
];

/**
 * Compone l'elenco dei fatti di una variante: la base comune, con eventuali
 * riscritture, più le affermazioni proprie della variante (fra cui i nodi che
 * nessun indizio prova e che vivono soltanto nelle dichiarazioni dei ruoli).
 */
export function factsFor(extra: FactDef[], overrides: Record<string, string> = {}): FactDef[] {
  const base = BASE_FACTS.map((f) => {
    const text = overrides[f.id];
    return text ? { ...f, text } : f;
  });
  return [...base, ...extra];
}
