import type { ClueDef, FactDef } from '@meridien/engine';

/**
 * «L'ultimo valzer» — fatti e indizi.
 *
 * Gli indizi sono gli stessi in tutte e tre le varianti: cambia soltanto ciò
 * che se ne deduce. Un indizio che nella variante A è il perno, nella variante
 * B documenta un segreto innocente. Per questo il catalogo dei fatti è comune:
 * i fatti sono tutti veri in tutte le varianti, sono le inferenze a cambiare.
 */

/** Fatti noti a tutti dal primo minuto: nessun indizio li rivela. */
export const COMMON_FACTS: FactDef[] = [
  {
    id: 'fact.crollo-ultimo-valzer',
    text: 'Ilde Ferrante si è accasciata sul palco alle 23:24, all’ottava battuta dell’ultimo valzer, e non ha più risposto.',
    kind: 'tempo',
    common: true,
  },
  {
    id: 'fact.bicchiere-sul-leggio',
    text: 'Sul leggio del palco c’era un bicchiere. Centoventi persone hanno visto Ilde alzarlo alle 23:10 e posarlo.',
    kind: 'oggetto',
    common: true,
  },
  {
    id: 'fact.brindisi-al-bar',
    text: 'Alle 22:08, al bar della sala, c’è stato un brindisi per i vent’anni di carriera di Ilde Ferrante.',
    kind: 'tempo',
    common: true,
  },
  {
    id: 'fact.intervallo-lungo',
    text: 'Fra le 21:40 e le 22:00 l’orchestra ha taciuto: l’intervallo è durato venti minuti buoni.',
    kind: 'tempo',
    common: true,
  },
  {
    id: 'fact.serata-incisa',
    text: 'Tutta la serata è stata incisa su nastro dalla sala di registrazione dell’albergo, primo e secondo tempo.',
    kind: 'oggetto',
    common: true,
  },
];

/** Fatti che si ottengono soltanto trovando l'indizio corrispondente. */
export const EVIDENCE_FACTS: FactDef[] = [
  {
    id: 'fact.spartito-sostituito',
    text: 'Nella cartella dell’ultimo valzer c’è una copia recente: non lo spartito che Ilde annotava a matita da due stagioni.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.copista-lanzoni',
    text: 'La copia è vergata a mano dal maestro Lanzoni: stessa china, stesso modo di chiudere le stanghette.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.piega-polverosa',
    text: 'Nella piega della terza pagina è rimasta una polvere bianca finissima che nel resto della cartella non c’è.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.canzone-firmata-ilde',
    text: 'All’ufficio del diritto d’autore l’ultimo valzer risulta depositato il 14 gennaio a nome della sola Ilde Ferrante.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.annuncio-paternita',
    text: 'Sul nastro, prima del primo tempo, Ilde presenta il valzer al pubblico come «parole e musica mie».',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.lanzoni-lettera',
    text: 'Nella tasca del frac di Lanzoni c’è una lettera per Ilde, ancora chiusa, con l’intestazione dell’ufficio del diritto d’autore.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.lanzoni-guanti',
    text: 'Lanzoni ha diretto tutta la serata con i guanti bianchi. In due stagioni non li aveva mai messi.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.chiave-duplicata',
    text: 'Della chiave del primo camerino esiste un secondo esemplare, dato in consegna all’orchestra nel 1967 e mai restituito.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.camerino-chiuso',
    text: 'Il primo camerino è rimasto chiuso a chiave dalle 20:35 alle 21:40, con la chiave del bancone appesa al suo gancio.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.pastiglie-mancanti',
    text: 'Dall’astuccio delle pastiglie per la voce, che Ilde teneva infilato nella piega dello spartito, ne mancano due.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.pastiglie-intervallo',
    text: 'Ilde prendeva due pastiglie all’intervallo, sempre, e in nessun altro momento della serata.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.calici-gemelli',
    text: 'Al bar erano pronti due calici identici, piede segnato a smeriglio, che nessuno risulta aver ordinato.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.calice-lavato',
    text: 'Il calice tolto dal leggio è stato lavato e asciugato prima che a qualcuno venisse in mente di chiederlo.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.rossetto-assente',
    text: 'Sul bicchiere del leggio non c’è traccia del rossetto di Ilde, che è invece su tutto il resto delle sue cose.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.delia-al-bar',
    text: 'Delia Marcantonio è rimasta al banco del bar dalle 21:56 alle 22:12, con le spalle alla sala.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.vassoio-in-piu',
    text: 'In cucina è rientrato un vassoio con un calice in più di quelli che erano usciti.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.porta-servizio-aperta',
    text: 'La porta di servizio fra il bar e la cucina è rimasta accostata per tutta la serata.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.delia-al-leggio',
    text: 'Alle 22:14 Delia Marcantonio è salita sul palco vuoto e ha posato lei stessa un bicchiere sul leggio.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.locandina-coperta',
    text: 'Sulla locandina del gala il nome di Delia Marcantonio è coperto da una fascetta di carta incollata nel pomeriggio.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.delia-provino',
    text: 'Il telegramma che fissava il provino di Delia a Roma per il 2 marzo è stato disdetto il 27 febbraio, dall’ufficio di Bergonzi.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.articolo-scritto',
    text: 'L’articolo della Ravasio era già battuto a macchina alle 21:00: annuncia il ritorno all’incisione di Ilde e non nomina nessun’altra.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.contratto-altra-voce',
    text: 'Il contratto d’incisione firmato da Bergonzi il 20 febbraio porta il nome di Delia Marcantonio, non quello di Ilde.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.nastro-tagliato',
    text: 'Nella bobina della serata mancano quattro minuti, fra le 22:20 e le 22:24: il nastro è stato tagliato e giuntato a mano.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.voce-incrinata',
    text: 'Sul nastro, nel punto che corrisponde alle 22:32, la voce di Ilde si incrina per la prima volta e lei ripete la battuta.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.boccetta-rabboccata',
    text: 'La boccetta di miele e limone del camerino è più piena di come Ilde l’aveva lasciata e il tappo è rimesso al contrario.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.registratore-a-vuoto',
    text: 'Il contagiri dice che il registratore ha girato dalle 22:05 alle 22:15 su nastro muto: in quei minuti nessuno stava incidendo.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.copie-non-registrate',
    text: 'Nell’armadietto di lamiera ci sono undici bobine copiate che non compaiono su nessun registro dell’albergo.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.nastro-del-sessantasette',
    text: 'Una bobina del 1967 conserva una conversazione che Ilde aveva chiesto per iscritto di distruggere.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.sivori-licenziato',
    text: 'Sivori aveva in tasca la lettera di licenziamento, con effetto dal 1° marzo, firmata su segnalazione di Ilde.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.telefonata-genova',
    text: 'Alle 21:05, dal centralino di servizio, è partita una chiamata a Genova durata undici minuti e non addebitata a nessuna camera.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.corridoio-al-buio',
    text: 'Nel corridoio degli artisti la lampada di mezzo è saltata alle 22:00 e nessuno l’ha cambiata fino alla fine della serata.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.veleno-ritardato',
    text: 'Il preparato non agisce subito: fra il momento in cui viene preso e il momento in cui si vede passa più di un’ora.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.ilde-seduta-due-volte',
    text: 'Ilde si è seduta due volte prima dell’ultimo valzer: una in corridoio verso le 22:50, una dietro il sipario alle 23:05.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.lastre-bruciate',
    text: 'Pastorino ha bruciato due lastre nel secchio di zinco del corridoio prima della fine della serata.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.assegno-contessa',
    text: 'La contessa Sforza Ghirlanda ha firmato quella sera un assegno di due milioni all’ordine di Ilde Ferrante.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.cassa-ammanco',
    text: 'Nella cassa della direzione mancano centomila lire, coperte da una ricevuta di comodo firmata Ugolini.',
    kind: 'oggetto',
    common: false,
  },
];

/**
 * Fatti che nessun indizio rivela: esistono solo perché qualcuno li afferma.
 * Servono al rilevatore di contraddizioni e non sono mai derivabili dalle prove.
 */
export const DECLARED_FACTS: FactDef[] = [
  {
    id: 'fact.dich-camerino-aperto',
    text: 'Il primo camerino è rimasto aperto per tutta la serata, come sempre nelle sere di gala.',
    kind: 'dichiarazione',
    common: false,
  },
  {
    id: 'fact.dich-copia-di-ilde',
    text: 'La copia dell’ultimo valzer che sta nella cartella l’ha scritta Ilde di suo pugno, la settimana scorsa.',
    kind: 'dichiarazione',
    common: false,
  },
  {
    id: 'fact.dich-corridoio-illuminato',
    text: 'Nel corridoio degli artisti la luce ha funzionato regolarmente dal principio alla fine della serata.',
    kind: 'dichiarazione',
    common: false,
  },
  {
    id: 'fact.dich-bicchiere-intatto',
    text: 'Il bicchiere del leggio non è stato toccato da nessuno dopo le 23:24: è rimasto dove Ilde l’aveva posato.',
    kind: 'dichiarazione',
    common: false,
  },
  {
    id: 'fact.dich-registratore-spento',
    text: 'Il registratore è rimasto spento dalla fine del primo tempo fino all’inizio dell’incisione di prova.',
    kind: 'dichiarazione',
    common: false,
  },
];

/** Catalogo completo dei fatti di una variante, prima delle aggiunte locali. */
export const ALL_FACTS: FactDef[] = [...COMMON_FACTS, ...EVIDENCE_FACTS, ...DECLARED_FACTS];

/** I trentaquattro indizi del caso. */
export const clues: ClueDef[] = [
  {
    id: 'clue.spartito-copia',
    title: 'La copia nella cartella',
    text: 'I sei fogli dell’ultimo valzer sono puliti: nessuna matita, nessun taglio di respiro segnato. La carta è di due mesi fa e la mano che l’ha scritta non è quella di Ilde.',
    kind: 'documento',
    icon: 'spartito',
    reveals: ['fact.spartito-sostituito', 'fact.copista-lanzoni'],
    requires: [],
    objectId: 'obj.spartito',
  },
  {
    id: 'clue.piega-terza-pagina',
    title: 'La piega della terza pagina',
    text: 'La terza pagina è piegata in tre, come tutte. Dentro la piega, contro la luce, resta una polvere bianca che non è gesso e non è cipria.',
    kind: 'fisico',
    icon: 'lente',
    reveals: ['fact.piega-polverosa'],
    requires: [],
    objectId: 'obj.spartito',
  },
  {
    id: 'clue.deposito-diritti',
    title: 'La ricevuta di deposito',
    text: 'Ricevuta dell’ufficio del diritto d’autore, 14 gennaio 1969: «L’ultimo valzer», parole e musica, deposito a nome di Ferrante Ilde. Un nome solo, nessun coautore.',
    kind: 'documento',
    icon: 'timbro',
    reveals: ['fact.canzone-firmata-ilde'],
    requires: [],
  },
  {
    id: 'clue.annuncio-nastro',
    title: 'L’annuncio prima del primo tempo',
    text: 'Sul nastro, prima che l’orchestra attacchi, si sente Ilde al microfono: «Adesso una cosa nuova. Parole e musica mie». In sala ridono, qualcuno applaude.',
    kind: 'sonoro',
    icon: 'bobina',
    reveals: ['fact.annuncio-paternita'],
    requires: [],
    objectId: 'obj.bobina',
  },
  {
    id: 'clue.lettera-chiusa',
    title: 'La lettera mai aperta',
    text: 'Busta con l’intestazione dell’ufficio del diritto d’autore, indirizzata a Ilde Ferrante, ancora chiusa. È stata piegata in quattro per stare in una tasca da frac.',
    kind: 'documento',
    icon: 'lettera',
    reveals: ['fact.lanzoni-lettera'],
    requires: [],
  },
  {
    id: 'clue.guanti-bianchi',
    title: 'I guanti del maestro',
    text: 'Il maestro ha diretto con i guanti bianchi da sera. I professori d’orchestra se lo sono detti fra loro: in due stagioni non glieli avevano mai visti.',
    kind: 'osservazione',
    icon: 'guanto',
    reveals: ['fact.lanzoni-guanti'],
    requires: [],
  },
  {
    id: 'clue.chiave-orchestra',
    title: 'La chiave dell’orchestra',
    text: 'Nella custodia del leggio, sotto la fodera, una chiave di ottone con il fiocco rosso sfilacciato. Il fiocco è quello che l’albergo usava nel 1967.',
    kind: 'fisico',
    icon: 'chiave',
    reveals: ['fact.chiave-duplicata'],
    requires: [],
    objectId: 'obj.chiave',
  },
  {
    id: 'clue.registro-chiavi',
    title: 'Il registro delle chiavi',
    text: 'Colonna dei camerini: chiave uno ritirata alle 20:35, riconsegnata alle 21:40. In mezzo, nessuna riga. Il gancio del bancone non è mai rimasto vuoto.',
    kind: 'documento',
    icon: 'registro',
    reveals: ['fact.camerino-chiuso'],
    requires: [],
    objectId: 'obj.chiave',
  },
  {
    id: 'clue.astuccio-pastiglie',
    title: 'L’astuccio delle pastiglie',
    text: 'Scatoletta di latta da dodici pastiglie alla propoli. Ne restano dieci. Il coperchio è chiuso male, come chiude chi ha fretta e non ha le unghie lunghe.',
    kind: 'fisico',
    icon: 'astuccio',
    reveals: ['fact.pastiglie-mancanti'],
    requires: [],
    objectId: 'obj.astuccio',
  },
  {
    id: 'clue.abitudine-voce',
    title: 'L’abitudine della voce',
    text: 'La governante lo dice come si dice un orario dei treni: due pastiglie all’intervallo, mai prima di entrare, mai dopo. Ilde diceva che prima le seccavano la gola.',
    kind: 'testimonianza',
    icon: 'voce',
    reveals: ['fact.pastiglie-intervallo'],
    requires: [],
  },
  {
    id: 'clue.calici-gemelli',
    title: 'I due calici gemelli',
    text: 'Sul ripiano del bar, due calici uguali, piede segnato a smeriglio con una riga. Sul conto della serata non risultano: nessuno li ha ordinati e nessuno li ha pagati.',
    kind: 'fisico',
    icon: 'calice',
    reveals: ['fact.calici-gemelli'],
    requires: [],
    objectId: 'obj.calice',
  },
  {
    id: 'clue.calice-lavato',
    title: 'Il calice già lavato',
    text: 'Il ragazzo del banco lo ricorda perché gli è parso strano: il bicchiere del leggio era già lavato e capovolto sul panno quando gli hanno detto di non toccare niente.',
    kind: 'testimonianza',
    icon: 'panno',
    reveals: ['fact.calice-lavato'],
    requires: [],
  },
  {
    id: 'clue.orlo-pulito',
    title: 'L’orlo senza rossetto',
    text: 'Il bicchiere raccolto sul leggio ha l’orlo netto. Sul microfono, sul tovagliolo e sulla tazza del camerino il segno del rossetto c’è, e si vede da lontano.',
    kind: 'fisico',
    icon: 'calice',
    reveals: ['fact.rossetto-assente'],
    requires: [],
    objectId: 'obj.calice',
  },
  {
    id: 'clue.conto-del-bar',
    title: 'Il conto del bar',
    text: 'Scontrini in ordine d’ora. Dalle 21:56 alle 22:12 tutte le consumazioni sono battute al posto tre del banco, quello d’angolo, e firmate con la sigla di Delia Marcantonio.',
    kind: 'documento',
    icon: 'conto',
    reveals: ['fact.delia-al-bar'],
    requires: [],
  },
  {
    id: 'clue.conta-vassoi',
    title: 'La conta dei vassoi',
    text: 'Il capocuoco conta i vassoi come conta le uova. Ne è rientrato uno con un calice in più di quelli usciti, e la porta di servizio è rimasta accostata tutta la sera.',
    kind: 'documento',
    icon: 'vassoio',
    reveals: ['fact.vassoio-in-piu', 'fact.porta-servizio-aperta'],
    requires: [],
  },
  {
    id: 'clue.fotografia-leggio',
    title: 'La lastra del palco vuoto',
    text: 'Lastra numero sette: palco vuoto, orchestra in pausa, una figura in abito lungo di spalle che posa un bicchiere sul leggio. L’orologio del fondale segna le 22:14.',
    kind: 'fisico',
    icon: 'lastra',
    reveals: ['fact.delia-al-leggio'],
    requires: [],
    objectId: 'obj.macchina-foto',
  },
  {
    id: 'clue.locandina-fascetta',
    title: 'La fascetta sulla locandina',
    text: 'Sotto il nome di Ilde Ferrante, una fascetta di carta avorio incollata di fresco. Contro la lampada si legge quello che copre: «con Delia Marcantonio».',
    kind: 'fisico',
    icon: 'locandina',
    reveals: ['fact.locandina-coperta'],
    requires: [],
    objectId: 'obj.locandina',
  },
  {
    id: 'clue.telegramma-disdetto',
    title: 'Il telegramma disdetto',
    text: 'Telegramma del 27 febbraio, ufficio Bergonzi: «Provino Roma 2 marzo annullato punto seguirà lettera». Il destinatario è Delia Marcantonio, l’ora è le 18:40.',
    kind: 'documento',
    icon: 'telegramma',
    reveals: ['fact.delia-provino'],
    requires: [],
  },
  {
    id: 'clue.bozza-articolo',
    title: 'La bozza dell’articolo',
    text: 'Tre cartelle battute a macchina, timbrate dalla portineria alle 21:00. Titolo: «Il ritorno di Ilde Ferrante all’incisione». Nel pezzo non compare nessun altro nome.',
    kind: 'documento',
    icon: 'macchina-scrivere',
    reveals: ['fact.articolo-scritto'],
    requires: [],
  },
  {
    id: 'clue.contratto-incisione',
    title: 'Il contratto del venti febbraio',
    text: 'Contratto d’incisione per quattro facciate, firmato Bergonzi il 20 febbraio. Sulla riga dell’artista, battuto a macchina, il nome di Delia Marcantonio.',
    kind: 'documento',
    icon: 'contratto',
    reveals: ['fact.contratto-altra-voce'],
    requires: [],
  },
  {
    id: 'clue.giunta-nastro',
    title: 'La giunta sul nastro',
    text: 'A due terzi della bobina il nastro è tagliato di sbieco e rincollato con la carta gommata. Mancano quattro minuti, fra le 22:20 e le 22:24.',
    kind: 'fisico',
    icon: 'bobina',
    reveals: ['fact.nastro-tagliato'],
    requires: [],
    objectId: 'obj.bobina',
  },
  {
    id: 'clue.riascolto-nastro',
    title: 'Il riascolto del secondo tempo',
    text: 'Rimettendo il nastro dal principio, al punto delle 22:32 la voce si incrina su una nota tenuta. Ilde si ferma, ride, ripete la battuta. Poi va avanti come niente.',
    kind: 'sonoro',
    icon: 'bobina',
    reveals: ['fact.voce-incrinata'],
    requires: ['clue.giunta-nastro'],
    objectId: 'obj.bobina',
  },
  {
    id: 'clue.boccetta-livello',
    title: 'Il livello della boccetta',
    text: 'La boccetta di miele e limone è più piena di come è stata lasciata: il segno unto sul vetro è sotto il livello. Il tappo di sughero è rimesso al contrario.',
    kind: 'fisico',
    icon: 'boccetta',
    reveals: ['fact.boccetta-rabboccata'],
    requires: [],
    objectId: 'obj.boccetta',
  },
  {
    id: 'clue.contagiri',
    title: 'Il contagiri',
    text: 'Il contagiri del registratore avanza di dieci minuti di nastro fra le 22:05 e le 22:15. Su quei dieci minuti non c’è musica: c’è il ronzio della sala vuota.',
    kind: 'documento',
    icon: 'registratore',
    reveals: ['fact.registratore-a-vuoto'],
    requires: [],
    objectId: 'obj.registratore',
  },
  {
    id: 'clue.armadietto-bobine',
    title: 'L’armadietto di lamiera',
    text: 'Undici bobine in fila, etichette a matita con date fra il 1966 e il 1969. Nessuna di queste date compare sul registro delle incisioni dell’albergo.',
    kind: 'fisico',
    icon: 'armadietto',
    reveals: ['fact.copie-non-registrate'],
    requires: [],
  },
  {
    id: 'clue.nastro-vecchio',
    title: 'La bobina del Sessantasette',
    text: 'Bobina senza etichetta, nastro vecchio. Sopra, due voci in una stanza: una è di Ilde, l’altra chiede una cifra. In fondo alla scatola, un biglietto: «distruggere».',
    kind: 'sonoro',
    icon: 'bobina',
    reveals: ['fact.nastro-del-sessantasette'],
    requires: [],
    objectId: 'obj.bobina',
  },
  {
    id: 'clue.lettera-licenziamento',
    title: 'La lettera di licenziamento',
    text: 'Carta intestata della direzione, data 24 febbraio: rapporto risolto con effetto dal 1° marzo. In calce, a penna: «su segnalazione della signora Ferrante».',
    kind: 'documento',
    icon: 'lettera',
    reveals: ['fact.sivori-licenziato'],
    requires: [],
  },
  {
    id: 'clue.registro-telefonate',
    title: 'Il registro delle telefonate',
    text: 'Foglio del centralino di servizio: 21:05, Genova, undici minuti, nessuna camera addebitata. Accanto, di mano della centralinista, un trattino e niente altro.',
    kind: 'documento',
    icon: 'centralino',
    reveals: ['fact.telefonata-genova'],
    requires: [],
  },
  {
    id: 'clue.lampada-saltata',
    title: 'La lampada di mezzo',
    text: 'Nel corridoio degli artisti la seconda lampada è bruciata. L’elettricista la dà per saltata alle 22:00 e non l’ha cambiata: dice che a quell’ora non passa nessuno.',
    kind: 'osservazione',
    icon: 'lampada',
    reveals: ['fact.corridoio-al-buio'],
    requires: [],
  },
  {
    id: 'clue.foglio-farmacista',
    title: 'Il foglio del farmacista',
    text: 'Foglio di prontuario piegato in due, con una riga sottolineata a matita: il preparato non dà segno prima di un’ora, e può metterci anche il doppio.',
    kind: 'documento',
    icon: 'prontuario',
    reveals: ['fact.veleno-ritardato'],
    requires: [],
  },
  {
    id: 'clue.appunti-cameriere',
    title: 'Gli appunti del cameriere di sala',
    text: 'Sul retro della lista delle portate, a matita: «22:50 signora seduta in corridoio, chiede acqua» e «23:05 seduta dietro il sipario, non vuole niente».',
    kind: 'testimonianza',
    icon: 'taccuino',
    reveals: ['fact.ilde-seduta-due-volte'],
    requires: [],
  },
  {
    id: 'clue.lastre-bruciate',
    title: 'Le lastre nel secchio',
    text: 'Nel secchio di zinco del corridoio, due lastre da sei per nove annerite dalla fiamma. L’emulsione è andata, il vetro no: si vedono due sagome in piedi.',
    kind: 'fisico',
    icon: 'lastra',
    reveals: ['fact.lastre-bruciate'],
    requires: [],
    objectId: 'obj.macchina-foto',
  },
  {
    id: 'clue.matrice-assegno',
    title: 'La matrice dell’assegno',
    text: 'Libretto d’assegni della contessa, ultima matrice compilata: due milioni, all’ordine di Ferrante Ilde, data di stasera. Sotto, cancellata due volte, la parola «ultimo».',
    kind: 'documento',
    icon: 'assegno',
    reveals: ['fact.assegno-contessa'],
    requires: [],
  },
  {
    id: 'clue.ricevuta-comodo',
    title: 'La ricevuta di comodo',
    text: 'Nel cassetto della direzione, una ricevuta per centomila lire di «servizi d’orchestra» che l’orchestra non ha reso. La firma in calce è di Ugolini.',
    kind: 'documento',
    icon: 'ricevuta',
    reveals: ['fact.cassa-ammanco'],
    requires: [],
  },
];
