import type { ClueDef, FactDef } from '@meridien/engine';

/**
 * I trentasei indizi del caso e il vocabolario dei fatti.
 *
 * Gli indizi sono definiti una volta sola: il testo è una constatazione
 * oggettiva, valida in tutte e tre le varianti. Il *significato* di ciò che si
 * è trovato sta nel fatto collegato, e il testo del fatto lo riscrive ogni
 * variante con `factsWith()`. Così lo stesso registro, la stessa ricevuta e la
 * stessa impronta possono accusare persone diverse senza mai mentire.
 */

export const CLUES: ClueDef[] = [
  {
    id: 'clue.toppa-libera',
    title: 'Il buco della serratura',
    text: 'Guardando dalla toppa della 404 si vedevano il tappeto e il piede del letto. Dall’altra parte, nella serratura, non c’era nessuna chiave.',
    kind: 'osservazione',
    icon: 'serratura',
    reveals: ['fact.toppa'],
    requires: [],
    objectId: 'obj.chiave-fiocco',
  },
  {
    id: 'clue.cera-serratura',
    title: 'Cera nella serratura',
    text: 'Nella gola della serratura della 404 restano scaglie di cera vergine, del tipo che i fabbri usano per prendere l’impronta di una chiave a doppia mandata.',
    kind: 'fisico',
    icon: 'cera',
    reveals: ['fact.calco'],
    requires: [],
  },
  {
    id: 'clue.doppione-fabbro',
    title: 'Ricevuta del fabbro',
    text: 'Ferramenta di Laigueglia, 8 gennaio: «copia chiave doppia mandata, camera 404». La riga dell’intestatario è scritta a matita, con una calligrafia che non è quella dell’impiegato.',
    kind: 'documento',
    icon: 'ricevuta',
    reveals: ['fact.doppione'],
    requires: [],
  },
  {
    id: 'clue.passe-partout-mancante',
    title: 'Il passe-partout dei piani',
    text: 'Nel quadro dietro il bancone il passe-partout ha un anello rosso e un cartellino: chi lo ritira firma, chi lo riporta firma di nuovo, con l’ora.',
    kind: 'osservazione',
    icon: 'passepartout',
    reveals: ['fact.passe'],
    requires: [],
    objectId: 'obj.passe-partout',
  },
  {
    id: 'clue.gancio-vuoto',
    title: 'Il gancio della 404',
    text: 'Nel quadro delle chiavi il gancio della 404 è vuoto dalle nove di sera. Accanto pende il cartellino con l’ora di consegna, scritto a mano.',
    kind: 'osservazione',
    icon: 'gancio',
    reveals: ['fact.gancio'],
    requires: [],
  },
  {
    id: 'clue.registro-chiavi',
    title: 'Il registro delle chiavi',
    text: 'Il portiere annota consegne e riconsegne con l’ora. La riga della 404 è seguita da quella della 402, scritta di seguito con la stessa penna e senza spazi.',
    kind: 'documento',
    icon: 'registro',
    reveals: ['fact.registro-chiavi'],
    requires: [],
    objectId: 'obj.registro-chiavi',
  },
  {
    id: 'clue.olio-cardine',
    title: 'I cardini dietro l’armadio',
    text: 'Dietro l’armadio della 404 c’è la porta di servizio. I tre cardini sono lucidi d’olio fresco; il legno intorno è coperto di polvere vecchia.',
    kind: 'fisico',
    icon: 'olio',
    reveals: ['fact.cardini'],
    requires: [],
  },
  {
    id: 'clue.porta-passaggio',
    title: 'La porta del passaggio',
    text: 'Al quarto piano la porta del passaggio di servizio non è accostata: qualcuno ha piegato in quattro un tovagliolo di lino e l’ha incastrato sotto il battente.',
    kind: 'osservazione',
    icon: 'porta',
    reveals: ['fact.porta-passaggio'],
    requires: [],
  },
  {
    id: 'clue.impronta-farina',
    title: 'L’impronta infarinata',
    text: 'Un sacco di farina sfondato ieri ha lasciato una striscia bianca dalla dispensa alla scala. Sul cemento resta una suola stampata netta, con il tacco consumato da un lato.',
    kind: 'fisico',
    icon: 'impronta',
    reveals: ['fact.impronta'],
    requires: [],
  },
  {
    id: 'clue.filo-lame',
    title: 'Il filo sul gancio',
    text: 'Nel passaggio, all’altezza delle spalle, un gancio da carrello. Vi è rimasto impigliato un filo lungo tre dita, strappato di fresco.',
    kind: 'fisico',
    icon: 'filo',
    reveals: ['fact.filo'],
    requires: [],
  },
  {
    id: 'clue.voci-nella-404',
    title: 'Le voci dietro la porta',
    text: 'Una cameriera ai piani ha sentito parlare dentro la 404 mentre rifaceva il carrello. Due voci: quella del proprietario e un’altra. Ricorda l’ora e mezza frase.',
    kind: 'testimonianza',
    icon: 'voci',
    reveals: ['fact.voci'],
    requires: [],
  },
  {
    id: 'clue.pausa-orchestra',
    title: 'Il foglio del maestro',
    text: 'Il maestro segna i pezzi eseguiti uno sotto l’altro. Fra due ballabili c’è una riga vuota e, di fianco, un’annotazione a matita con due orari.',
    kind: 'documento',
    icon: 'orchestra',
    reveals: ['fact.orchestra'],
    requires: [],
  },
  {
    id: 'clue.registro-centralino',
    title: 'Il brogliaccio del centralino',
    text: 'La centralinista annota ogni collegamento: interno, ora, durata in secondi. Le righe che riguardano la 404 sono tre e non tornano fra loro.',
    kind: 'documento',
    icon: 'centralino',
    reveals: ['fact.centralino'],
    requires: [],
  },
  {
    id: 'clue.cuffie-marisa',
    title: 'Quel che arrivava in cuffia',
    text: 'La centralinista resta in ascolto finché la comunicazione non parte. Ricorda con precisione che cosa si sentiva dalla 404 quando la linea è tornata.',
    kind: 'sonoro',
    icon: 'cuffia',
    reveals: ['fact.cuffie'],
    requires: [],
  },
  {
    id: 'clue.sveglia-avanti',
    title: 'La sveglia da viaggio',
    text: 'Sul comodino della 404, una sveglia da viaggio in cuoio, aperta e carica. Le lancette non coincidono con l’ora del centralino.',
    kind: 'fisico',
    icon: 'sveglia',
    reveals: ['fact.sveglia'],
    requires: [],
    objectId: 'obj.sveglia-viaggio',
  },
  {
    id: 'clue.orologio-sala',
    title: 'L’orologio della sala',
    text: 'L’orologio a muro della sala da ballo, sopra la porta dei musicisti. Il portiere lo carica ogni domenica e conosce a memoria il suo scarto.',
    kind: 'osservazione',
    icon: 'orologio',
    reveals: ['fact.orologio-sala'],
    requires: [],
  },
  {
    id: 'clue.polaroid-sala',
    title: 'La polaroid del brindisi',
    text: 'Una istantanea scattata in sala durante il ballo. Sullo sfondo, sopra le teste, l’orologio a muro con le lancette perfettamente leggibili.',
    kind: 'fisico',
    icon: 'polaroid',
    reveals: ['fact.polaroid'],
    requires: [],
    objectId: 'obj.polaroid',
  },
  {
    id: 'clue.foto-scartata',
    title: 'La stampa scartata',
    text: 'Nel cestino del ripostiglio che il fotografo usa come camera oscura, una stampa piegata in quattro. È mossa, e per questo è finita lì.',
    kind: 'fisico',
    icon: 'negativo',
    reveals: ['fact.foto-scartata'],
    requires: [],
  },
  {
    id: 'clue.quaderno-quadro',
    title: 'Il quaderno dei turni',
    text: 'L’elettricista segna ogni intervento con l’ora e il numero del quadro. La pagina del 12 gennaio porta due righe e una cancellatura.',
    kind: 'documento',
    icon: 'quaderno',
    reveals: ['fact.quaderno-turni'],
    requires: [],
    objectId: 'obj.taccuino-turni',
  },
  {
    id: 'clue.leva-abbassata',
    title: 'La leva del quarto piano',
    text: 'Nel quadro elettrico, la leva della linea del quarto piano. La vernice intorno alla maniglia porta un’unghiata fresca, chiara sul grigio.',
    kind: 'fisico',
    icon: 'leva',
    reveals: ['fact.leva-quadro'],
    requires: [],
  },
  {
    id: 'clue.ascensore-fermo',
    title: 'Il fermo dell’ascensore',
    text: 'La cancellata dell’ascensore ha un fermo di sicurezza. Quando è inserito la cabina resta al piano, e in hall il quadro luminoso lo segnala con una lampadina gialla.',
    kind: 'osservazione',
    icon: 'ascensore',
    reveals: ['fact.ascensore'],
    requires: [],
  },
  {
    id: 'clue.cambiale',
    title: 'La cambiale in cassaforte',
    text: 'Nella cartella di Malaspina un effetto in bollo, importo in cifre e lettere, firma dell’obbligato in basso a destra. Scadenza: 31 gennaio.',
    kind: 'documento',
    icon: 'cambiale',
    reveals: ['fact.cambiale'],
    requires: [],
    objectId: 'obj.cambiale',
  },
  {
    id: 'clue.libro-conti-sala',
    title: 'Il libro della saletta',
    text: 'Il registro della saletta da gioco del primo piano: data, tavolo, saldo di fine serata. Le ultime pagine sono compilate con una calligrafia più stretta.',
    kind: 'documento',
    icon: 'libro',
    reveals: ['fact.conti-sala'],
    requires: [],
  },
  {
    id: 'clue.lettera-ricatto',
    title: 'La lettera mai imbucata',
    text: 'Nel cassetto della scrivania della 404, un foglio intestato piegato in tre e mai spedito. Poche righe, nessuna intestazione, una data in alto.',
    kind: 'documento',
    icon: 'lettera',
    reveals: ['fact.lettera'],
    requires: [],
    objectId: 'obj.lettera-ricatto',
  },
  {
    id: 'clue.busta-vuota',
    title: 'La busta vuota',
    text: 'Nel cestino della 404 una busta aperta con il tagliacarte, taglio netto. Sul davanti due iniziali a inchiostro; dentro, niente.',
    kind: 'fisico',
    icon: 'busta',
    reveals: ['fact.busta'],
    requires: [],
  },
  {
    id: 'clue.telegramma-notaio',
    title: 'Il telegramma',
    text: 'Un telegramma arrivato alle 18:20 e salito in suite con il vassoio del tè. Testo di undici parole, firmato con il nome di uno studio notarile di Genova.',
    kind: 'documento',
    icon: 'telegramma',
    reveals: ['fact.notaio-telegramma'],
    requires: [],
  },
  {
    id: 'clue.agenda-malaspina',
    title: 'L’agenda del proprietario',
    text: 'L’agenda di Malaspina, aperta sulla settimana in corso. Alcune righe sono cancellate con un tratto solo, altre riscritte sopra con inchiostro diverso.',
    kind: 'documento',
    icon: 'agenda',
    reveals: ['fact.agenda'],
    requires: [],
  },
  {
    id: 'clue.scarpe-asciutte',
    title: 'Le scarpe asciutte',
    text: 'Stanotte in terrazza si esce e si rientra con il sale addosso: le suole restano segnate per un’ora. In hall un paio di scarpe da sera è asciutto e lucido.',
    kind: 'osservazione',
    icon: 'scarpe',
    reveals: ['fact.scarpe'],
    requires: [],
  },
  {
    id: 'clue.finestra-socchiusa',
    title: 'La finestra della suite',
    text: 'La finestra della 404 dà sulla scogliera, quattro piani più sotto, senza cornicione né scala. È socchiusa e il fermo è arrugginito nella posizione aperta.',
    kind: 'osservazione',
    icon: 'finestra',
    reveals: ['fact.finestra'],
    requires: [],
  },
  {
    id: 'clue.bicchiere-due',
    title: 'I due bicchieri',
    text: 'Sul tavolino della 404, due bicchieri da cognac. Uno è stato usato, l’altro è ancora asciutto: versato e mai toccato.',
    kind: 'osservazione',
    icon: 'bicchieri',
    reveals: ['fact.bicchieri'],
    requires: [],
  },
  {
    id: 'clue.vassoio-intatto',
    title: 'Il vassoio nel corridoio',
    text: 'Il vassoio salito alle 21:40 è ancora sul carrello del corridoio, con il tovagliolo piegato come lo aveva messo la cucina e la teiera fredda.',
    kind: 'fisico',
    icon: 'vassoio',
    reveals: ['fact.vassoio'],
    requires: [],
  },
  {
    id: 'clue.guanto-spaiato',
    title: 'Il guanto spaiato',
    text: 'Sotto la poltrona della 404, un guanto lungo da sera, spaiato. Taglia piccola, bordo sfilacciato, e un rammendo fatto in casa sul polso.',
    kind: 'fisico',
    icon: 'guanto',
    reveals: ['fact.guanto'],
    requires: [],
  },
  {
    id: 'clue.fazzoletto-cifrato',
    title: 'Il fazzoletto cifrato',
    text: 'Un fazzoletto di lino con una cifra ricamata a mano, ripiegato dentro il portacenere della 404. Non è stato usato per fumare.',
    kind: 'fisico',
    icon: 'fazzoletto',
    reveals: ['fact.fazzoletto'],
    requires: [],
  },
  {
    id: 'clue.ricevuta-farmacia',
    title: 'La ricevuta della farmacia',
    text: 'Ricevuta della farmacia di Alassio, 11 gennaio, per un preparato da banco contro l’insonnia. È intestata a un ospite dell’albergo.',
    kind: 'documento',
    icon: 'ricevuta-farmacia',
    reveals: ['fact.farmacia'],
    requires: [],
  },
  {
    id: 'clue.biglietto-camerino',
    title: 'Il biglietto nello specchio',
    text: 'Nel camerino dietro il palco, infilato nella cornice dello specchio, un biglietto scritto a mano su carta dell’albergo. Nessuna firma, nessun nome.',
    kind: 'documento',
    icon: 'biglietto',
    reveals: ['fact.biglietto'],
    requires: [],
  },
  {
    id: 'clue.registro-lavanderia',
    title: 'Il registro della lavanderia',
    text: 'La lavanderia segna capi ritirati e riconsegnati con il numero di camera. Alla pagina del 12 gennaio una riga è stata aggiunta a sera, con altra penna.',
    kind: 'documento',
    icon: 'lavanderia',
    reveals: ['fact.lavanderia'],
    requires: [],
  },
];

/**
 * Vocabolario dei fatti. I cinque `common` sono noti a tutti fin dall’inizio;
 * gli altri trentasei corrispondono uno a uno agli indizi.
 * Le varianti riscrivono i testi con `factsWith()`: gli identificatori no.
 */
export const BASE_FACTS: FactDef[] = [
  {
    id: 'fact.porta-chiusa',
    text: 'La 404 è stata trovata chiusa a chiave, e la chiave della suite era rimasta dentro, sul comodino.',
    kind: 'luogo',
    common: true,
  },
  {
    id: 'fact.brindisi-mancato',
    text: 'Malaspina non è sceso per il brindisi delle 23, che aveva annunciato lui stesso agli invitati.',
    kind: 'tempo',
    common: true,
  },
  {
    id: 'fact.linea-caduta',
    text: 'La linea telefonica è caduta alle 22:40 e da allora torna a intermittenza, pochi minuti per volta.',
    kind: 'tempo',
    common: true,
  },
  {
    id: 'fact.strada-franata',
    text: 'La strada per Alassio è franata alle 20:10: da quell’ora nessuno è entrato nell’albergo e nessuno ne è uscito.',
    kind: 'luogo',
    common: true,
  },
  {
    id: 'fact.ballo-in-corso',
    text: 'Il Ballo d’Inverno è cominciato alle 21 in sala da ballo e non si è mai interrotto per più di un quarto d’ora.',
    kind: 'tempo',
    common: true,
  },

  {
    id: 'fact.toppa',
    text: 'Nella serratura della 404, dalla parte interna, non c’era nessuna chiave: la toppa era libera da parte a parte.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.calco',
    text: 'Nella serratura della 404 restano scaglie di cera da calco: qualcuno ne ha preso l’impronta.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.doppione',
    text: 'L’8 gennaio è stata ordinata una copia della chiave della 404 alla ferramenta di Laigueglia.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.passe',
    text: 'Il passe-partout dei piani va ritirato dietro firma nel quadro delle chiavi della hall.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.gancio',
    text: 'La chiave della 404 è stata ritirata alle 21:02 e il gancio è rimasto vuoto tutta la sera.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.registro-chiavi',
    text: 'Il registro delle chiavi porta, per la 404, un orario che non coincide con quello che tutti raccontano.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.cardini',
    text: 'I cardini della porta di servizio della 404 sono stati oliati di recente.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.porta-passaggio',
    text: 'La porta del passaggio di servizio al quarto piano è stata tenuta aperta con un tovagliolo piegato.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.impronta',
    text: 'Nella farina rovesciata è rimasta l’impronta di una suola da sera con il tacco consumato di lato.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.filo',
    text: 'Sul gancio del passaggio di servizio è rimasto impigliato un filo di stoffa da sera.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.voci',
    text: 'Dietro la porta della 404 si sono sentite due voci discutere, e una non era quella del proprietario.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.orchestra',
    text: 'Il foglio del maestro registra una interruzione del programma e i due orari che la delimitano.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.centralino',
    text: 'Il brogliaccio del centralino registra un collegamento con la 404 dopo la caduta della linea.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.cuffie',
    text: 'La centralinista ricorda che cosa si sentiva dalla 404 nell’ultimo collegamento della serata.',
    kind: 'dichiarazione',
    common: false,
  },
  {
    id: 'fact.sveglia',
    text: 'La sveglia da viaggio della 404 non segna la stessa ora del centralino.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.orologio-sala',
    text: 'L’orologio a muro della sala da ballo non segna la stessa ora del centralino.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.polaroid',
    text: 'Una istantanea scattata in sala mostra insieme una persona e l’orologio a muro.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.foto-scartata',
    text: 'Una stampa scartata perché mossa mostra un angolo dell’albergo che nessuno stava fotografando.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.quaderno-turni',
    text: 'Il quaderno dei turni riporta due interventi dell’elettricista nella serata del 12 gennaio.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.leva-quadro',
    text: 'La leva del quarto piano nel quadro elettrico è stata mossa a mano, di recente.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.ascensore',
    text: 'Il fermo di sicurezza dell’ascensore è stato inserito durante la serata: la cabina è rimasta a un piano solo.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.cambiale',
    text: 'Malaspina teneva in cassaforte una cambiale firmata da uno degli invitati, in scadenza a fine gennaio.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.conti-sala',
    text: 'Il libro della saletta da gioco mostra un ammanco che qualcuno ha coperto riscrivendo i saldi.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.lettera',
    text: 'Malaspina aveva scritto e non spedito una lettera che chiedeva qualcosa a qualcuno, con una scadenza.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.busta',
    text: 'Nel cestino della 404 c’è una busta aperta con due iniziali sul davanti e niente dentro.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.notaio-telegramma',
    text: 'Uno studio notarile di Genova ha telegrafato a Malaspina alle 18:20 del 12 gennaio.',
    kind: 'relazione',
    common: false,
  },
  {
    id: 'fact.agenda',
    text: 'L’agenda di Malaspina porta, per quella settimana, un appuntamento cancellato e riscritto.',
    kind: 'tempo',
    common: false,
  },
  {
    id: 'fact.scarpe',
    text: 'Chi dice di essere stato in terrazza stanotte dovrebbe avere le suole segnate dal sale: un paio non lo è.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.finestra',
    text: 'La finestra della 404 è socchiusa, ma sotto ci sono quattro piani di scogliera e nessun appiglio.',
    kind: 'luogo',
    common: false,
  },
  {
    id: 'fact.bicchieri',
    text: 'Nella 404 erano stati versati due cognac: uno bevuto, l’altro mai toccato.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.vassoio',
    text: 'Il vassoio salito alle 21:40 non è mai stato ritirato dentro la suite.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.guanto',
    text: 'Sotto la poltrona della 404 c’era un guanto da sera spaiato, rammendato a mano sul polso.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.fazzoletto',
    text: 'Nel portacenere della 404 c’era un fazzoletto di lino con una cifra ricamata.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.farmacia',
    text: 'Un ospite dell’albergo ha comprato ad Alassio, l’11 gennaio, un preparato contro l’insonnia.',
    kind: 'persona',
    common: false,
  },
  {
    id: 'fact.biglietto',
    text: 'Nel camerino c’era un biglietto anonimo, scritto su carta dell’albergo, con un’ora e un luogo.',
    kind: 'oggetto',
    common: false,
  },
  {
    id: 'fact.lavanderia',
    text: 'Il registro della lavanderia porta una riga aggiunta la sera del 12 gennaio, con un’altra penna.',
    kind: 'oggetto',
    common: false,
  },
];

/** Copia del vocabolario con i testi riscritti dalla variante. */
export function factsWith(overrides: Record<string, string>, extra: FactDef[] = []): FactDef[] {
  const rewritten = BASE_FACTS.map((f) => {
    const text = overrides[f.id];
    return text ? { ...f, text } : f;
  });
  return [...rewritten, ...extra];
}
